name       : kdav
version    : 5.96.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kdav-5.96.0.tar.xz : 94872e54c483ddf02d220b074285f979ad634f85a4c3fa8854e93952275a11ff
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
