name       : kdav
version    : 20.04.1
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kdav-20.04.1.tar.xz : b3d37c335d1df279bb91c2218362a859a117518e9f7a7fc08dde8c4e1b875e83
homepage   : https://community.kde.org/PIM
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
