name       : kdav
version    : 19.04.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/kdav-19.04.0.tar.xz : dce315916a993dbff7f7748538da91944b20df3cb6fc042e0d145d53904ff5d9
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
