name       : kdav
version    : 19.08.1
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kdav-19.08.1.tar.xz : 38f34f39e165ba3a843acbc9efc3296c111a6bfa8c5ba23e1f55f98860b84d41
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
