name       : kdav
version    : 19.12.1
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kdav-19.12.1.tar.xz : 5059a295f3ecd9046da6f5ecadab596b3e47c75c5090650a1d6cd1f86a8b7498
homepage   : https://community.kde.org/PIM
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
