name       : kdav
version    : 5.79.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kdav-5.79.0.tar.xz : d4f5d1f29de8f4b9cce6505f209d266dbd7b32ad8dc3e7fe1813fd4eacc2e394
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
