name       : kdav
version    : 5.91.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/kdav-5.91.0.tar.xz : 5b8cdae0d401dc24bf0cd98cdf35de30501111968923953fa687552ae61adc08
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
