name       : kdav
version    : 18.12.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kdav-18.12.1.tar.xz : e7bc0ba5b918e5969517d100a6d1de96e3ca4782731fb9eccbdf77fbc83d204f
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
