name       : kdav
version    : 19.04.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/kdav-19.04.2.tar.xz : 556c4912cfbd65b810c6a9d23b61dff0f59f70459cf52a81d7142cc750ef130c
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
