name       : kdav
version    : 5.106.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kdav-5.106.0.tar.xz : 173309587f5bc9d590e0ab7896aee7a5382bf73c858231d816231b28377ab4aa
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
