name       : kdav
version    : 19.04.3
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/kdav-19.04.3.tar.xz : f182a3ad6e23ff9e8165d11c3d4964e470e5d4d3f0183207cbe380f5c111af85
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
