name       : kdav
version    : 18.04.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kdav-18.04.0.tar.xz : 22c324c84aac61c5cf0bf353188b35a66278bec64ca4786291ddaab104a52b95
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : A DAV protocol implemention with KJobs.
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
