name       : kdav
version    : 17.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kdav-17.08.3.tar.xz : 2cf295490a9d3e7bf1554b39e0c3bb2272476b555b6915eeae977c8c3065fdec
license    : GPL-2.0
component  : desktop.library
summary    : A DAV protocol implemention with KJobs.
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
