name       : kdav
version    : 19.08.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/kdav-19.08.0.tar.xz : 8bfd0657c0eaa74068c7601208baacb9d11bc6574cd353d4d346473c6c43b6f6
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
