name       : kdav
version    : 5.81.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kdav-5.81.0.tar.xz : 0b00fdf902b1aeadfefe9caa11fad52a26f18e4c0e747c1bf8d9a1758b8bb133
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
