name       : kdav
version    : 18.04.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kdav-18.04.3.tar.xz : 50209d539ff824be4b7c65a92f413b8bd45fb6e9c4eaaa9fe2dd54bb963b2855
license    : GPL-2.0
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
