name       : kdav
version    : 5.87.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/kdav-5.87.0.tar.xz : bfccf61a54c7ddf10448ce735ac414ad26c5c39c1f762b0a7f85e2db38786169
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
