name       : kdav
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kdav-17.04.1.tar.xz : 333b24840747b0ab919c312d01691de7ec30f1ba09f757372a10375d40d94519
license    : GPL-2.0
component  : desktop.library
summary    : A DAV protocol implemention with KJobs.
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
