name       : kdav
version    : 18.04.1
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kdav-18.04.1.tar.xz : 2bedba63507e94253a8c01566d5b64094c52617d1349207d193a1378ccb94b99
license    : GPL-2.0
component  : desktop.library
optimize   : lto
summary    : A DAV protocol implemention with KJobs.
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
