name       : kdav
version    : 18.12.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kdav-18.12.3.tar.xz : 3ce99c65573d6374e91abff50b3a738515da07371f07c1b6e4b1800069a77c23
license    : GPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
