name       : kdav
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kdav-17.08.2.tar.xz : 6eba8297986b38f1a676e72b350ac2124f74e41ac7fb25bdc56759f62d46d033
license    : GPL-2.0
component  : desktop.library
summary    : A DAV protocol implemention with KJobs.
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
