name       : kdav
version    : 5.105.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kdav-5.105.0.tar.xz : 3de27547f16a32074387e049c17da94b13d82b0f5f86fb6abf06100a828be335
homepage   : https://community.kde.org/PIM
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : A DAV protocol implemention with KJobs
description: |
    A DAV protocol implemention with KJobs. Calendars and todos are supported, using either GroupDAV or CalDAV, and contacts are supported using GroupDAV or CardDAV.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
